### ISSUE TITLE
Sandbox breaks without .arc-env file

### ISSUE THREAD

**Issue by ShawnHosea** [begin-examples/node-hello-world#64]
For `npm start` to work with this example, you have to add a `.arc-env` file to the root with `@testing` inside of it.

`.arc-env` files are always set in the `.gitignore` file so anyone who begins a project with this starter will get an error when trying to start the sandbox environment. This means that right at the beginning of using this starter, users already have a bug to fix which might cause friction for onboarding the user.

**Comment by kristoferjoseph** [comment]
@ShawnHosea I am not able to reproduce this issue.
Can you do me a favor and pull down a new fresh clone and run `npm install` then `npm start` and update this issue with any errors you see?

Thanks!
